- version: 1.0.{build}
- image: Visual Studio 2017

-
  branches:
    except:
      - master
      - gh-pages
  before_build:
    - pwsh: dotnet --version
  build_script:
    - pwsh: dotnet build ./src/CityMap.csproj -c Release

- 
  branches:
    only:
    - master
  before_build:
    - pwsh: dotnet --version
  build_script:
    - pwsh: dotnet build ./src/CityMap.csproj -c Release
    - pwsh: dotnet publish ./src/CityMap.csproj -c Release -r win10-x64
    - pwsh: dotnet publish ./src/CityMap.csproj -c Release -r linux-x64
    - pwsh: dotnet publish ./src/CityMap.csproj -c Release -r osx-x64    
  artifacts:
  - path: 'src\bin\Release\netcoreapp2.0\win10-x64\publish'
    name: win10-x64
  - path: 'src\bin\Release\netcoreapp2.0\linux-x64\publish'
    name: linux-x64
  - path: 'src\bin\Release\netcoreapp2.0\osx-x64\publish'
    name: osx-x64
